apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: three-tier
type: Opaque
stringData:
  mongo-uri: "mongodb://admindb:password123@three-tier.cluster-ch2c82wwifaa.us-east-1.docdb.amazonaws.com:27017/?tls=true&retryWrites=false"
